Small changes to env var parsing and run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -9,9 +9,14 @@ fi
 # Handle different argument values
 case "$1" in
   install)
-    npm i --silent
-    num_dependencies=$(npm list --depth=0 | grep '├──' | wc -l)
-    echo "$num_dependencies dependencies installed..."
+    if npm i --silent; then
+      num_dependencies=$(npm list --depth=0 | grep '├──' | wc -l)
+      echo "$num_dependencies dependencies installed..."
+      exit 0
+    else
+      echo "Error installing dependencies. Dependencies not installed."
+      exit 1
+    fi
     ;;
   test)
     echo "Running tests..."
@@ -24,8 +29,9 @@ case "$1" in
       rc=$?
       if [ $rc -ne 0 ]; then
         echo "Error calculating metrics."
-        exit $rc
+        exit 1
       fi
+      exit 0
     else
       echo "Invalid argument. Please provide 'install', 'test', or a valid npmjs or GitHub URL."
       exit 1
